# Generated by Django 2.2.6 on 2019-10-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('userId', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=10)),
                ('dateofbirth', models.DateField()),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('battingarm', models.CharField(max_length=10)),
                ('bowlingarm', models.CharField(max_length=10)),
            ],
        ),
    ]
