# Generated by Django 2.2.6 on 2019-10-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
