# Generated by Django 2.2.6 on 2019-10-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20191019_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='dateofbirth',
            field=models.CharField(max_length=60),
        ),
    ]
