# Generated by Django 2.2.6 on 2019-10-23 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20191020_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('sessionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiryTime', models.BigIntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.PlayerProfile')),
            ],
        ),
    ]
