# Generated by Django 2.2.6 on 2019-11-01 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_playersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersession',
            name='userId',
            field=models.CharField(default='anjesh_gl', max_length=60, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playersession',
            name='sessionId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
